AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Infrastructure Code for provisioning ressources to for manual ES snapshots'

Parameters:
  Product:
    Type: String
    Description: Name of product
    MinLength: '1'
    MaxLength: '20'
  Environment:
    Type: String
    Description: Environment short sign
    MinLength: '1'
    MaxLength: '10'
  Team:
    Type: String
    Description: Team short sign
    MinLength: '1'
    MaxLength: '10'
Resources:
  ESSnapshotBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete # Delete or Retain is here the question - depending on the maturity level of this
    Properties:
      BucketName: !Sub '${Product}-${AWS::Region}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  ESSnapshotRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: !Sub '${Product}-role'
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "es.amazonaws.com"
            Action: 
              - "sts:AssumeRole"

      Path: "/"
      Policies:
        - PolicyName: !Sub '${Product}-policy-role'
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: 
                  - "s3:ListBucket"
                Resource: !Sub "arn:aws:s3:::${Product}-${AWS::Region}-${AWS::AccountId}"
              - 
                Effect: "Allow"
                Action: 
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:DeleteObject"
                Resource: !Sub "arn:aws:s3:::${Product}-${AWS::Region}-${AWS::AccountId}/*"
              - 
                Effect: "Allow"
                Action: 
                  - "iam:PassRole"
                Resource: !Sub "arn:aws:s3:::${Product}-${AWS::Region}-${AWS::AccountId}/*"